on: workflow_dispatch

jobs:
  build:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 aarch64
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            apt-get update
            apt-get install -y --no-install-recommends build-essential
            apt-get install -y --no-install-recommends python3-dev python3-pip
            python3 -m pip install -U pip
            pip3 install setuptools wheel
            python3 setup.py bdist_wheel
            # python3 _cross_platform.py #TODO
      - name: Save whl file to artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          retention-days: 1