# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: arm running test

on:
  workflow_dispatch

jobs:
  build_python3:
    name: ${{ matrix.arch_name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch_name: [ linux-arm64, android-arm64 ]
        python-version: [
            3.8
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and Build
      shell: bash
      run: |
        uname -a
        ls -l "`which python`*"
        python -m pip install -U pip 
        pip install setuptools wheel
        python setup.py sdist bdist_wheel
    - name: Save whl file to artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        retention-days: 1
