# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: armtest

on:
      workflow_dispatch

jobs:
   build_arm64_python38:
      # The host should always be Linux
      runs-on: ubuntu-20.04
      name:    Build on ubuntu-20.04 aarch64
      steps:
         -
            uses: actions/checkout@v2.1.0
         -
            uses: kirin123kirin/run-on-arch-action@master
            name: Run commands
            id:   runcmd
            with:
               arch:        aarch64
               distro:      python39
               githubToken: ${{ github.token }}
               run:         |
                            uname -a
                            env
                            find /usr/bin
                            which python && python -VV
                            which python3 && python3 -VV
#                            apt-get install -y --no-install-recommends build-essential
#                            apt-get install -y --no-install-recommends python3-dev python3-pip
#                            python3 -m pip install -U pip
#                            pip3 install setuptools wheel
#                            python3 setup.py bdist_wheel
#                            python3 -V
#         -
#            name: Save whl file to artifact
#            uses: actions/upload-artifact@v2
#            with:
#               name:           dist
#               path:           dist
#               retention-days: 1
