# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: mactest

on:
      workflow_dispatch

jobs:
   build_python:
      runs-on: ${{ matrix.platform }}
      strategy:
         max-parallel: 15
         matrix:
            platform: [
                  macos-latest
            ]
            python-version: [
                  2.7,
                  3.7,
            ]

      steps:
         -
            uses: actions/checkout@v2
         -
            name: Setup Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
               python-version: ${{ matrix.python-version }}

         -
            name:  Install and Build
            shell: bash
            run:   |
                   python -m pip install -U pip
                   pip install setuptools wheel
                   python setup.py sdist bdist_wheel
                   # python _cross_platform.py #TODO
