# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: armtest

on:
      workflow_dispatch

jobs:
   build_arm64_python:
      # The host should always be Linux
      runs-on: ubuntu-20.04
      name:    Build on ubuntu-20.04 aarch64
      strategy:
         max-parallel: 5
         matrix:
            python-version: [ python27,
                              python36,
                              python37,
#                              python38,
#                              python39,
            ]
      steps:
         -
            uses: actions/checkout@v2.1.0
         -
            uses: kirin123kirin/run-on-arch-action@master
            name: Run commands
            id:   runcmd
            with:
               arch:        aarch64
               distro: { { matrix.python-version } }
               githubToken: ${{ github.token }}
               run:         |
                            python setup.py bdist_wheel
         -
            name: Save whl file to artifact
            uses: actions/upload-artifact@v2
            with:
               name:           dist
               path:           dist
               retention-days: 1
