
name: excludetest

on:
      workflow_dispatch

jobs:
   build_python3:
      runs-on: ${{ matrix.platform }}
      strategy:
         max-parallel: 15
         matrix:
            platform: [
#                  ubuntu-latest,
                  windows-latest,
            ]
            python-version: [
                  2.7,
#                  3.7,
            ]
            exclude:
               -
                  platform:       windows-latest
                  python-version: 2.7


      steps:
         -
            uses: actions/checkout@v2
         -
            name: Setup Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
               python-version: ${{ matrix.python-version }}

         -
            name:  Install and Build
            shell: bash
            run:   |
                   python -m pip install -U pip
                   pip install setuptools wheel
                   python setup.py sdist bdist_wheel
                   # python _cross_platform.py #TODO
         -
            name: Save whl file to artifact
            uses: actions/upload-artifact@v2
            with:
               name:           dist
               path:           dist
               retention-days: 1

